# Generated by Django 5.2.17 on 2026-09-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Lost', 'L'), ('Found', 'F')], max_length=5)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contact_info', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='lost_found/image')),
            ],
        ),
    ]
